server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:

#    For local database config

#    url: jdbc:postgresql://localhost:5432/customer
#    username: amigoscode
#    password: password

# for docker database config
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet

cors:
  allowed-origins: "*"
  allowed-methods: "*"