aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc-secretsmanager:postgresql://awseb-e-zm3v3pm9un-stack-awsebrdsdatabase-h86478l0tpoz.cfzpaun3brxq.eu-west-1.rds.amazonaws.com:5432/ebdb
    username: test/full-stack/postgres
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
