name: CUstom params
on: 
  workflow_dispatch:
    inputs:
       customerName:
         description: "Add the name of the customer"
         type: string
         required: true
       isPremium:
        description: "Add premium feature"
        type: boolean
        required: false
       preferedTheme:
        description: "Frontend theme"
        type: choice
        default: light
        options:
         - "dark"
         - "light"
         - "high-contast"
jobs:
  test-argument:
    name: custom params
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "hello ${{ github.event.inputs.customerName}} your prefered theme is ${{ github.event.inputs.preferedTheme}}"
         
      
        
