name: New release
on:
  release:
    types:
      #- published
      - created
      
jobs:
  release-created:
   name: Relase created
   runs-on: ubuntu-latest
   steps:
    - name: Release message
      run: echo "A new release is created"
   
